### PR TITLE
'enable-media-replace-upload-done' action fix

### PR DESCRIPTION
**Pull request by krestaino**
Right now the action `enable-media-replace-upload-done` is only firing on search and replace. I just moved it to the end of the class so it's fired for both replace methods.

### CODE REVIEW

**Comment by krestaino** [comment]
@short-pixel-optimizer Hey just wanted to follow up here, did you get a chance to review this yet?

**Comment by bschuiling** [comment]
Hi, 

Yes, I was looking at the plugin today.  This was intentional since using the other replacement mode the URL's stay the same. 

I can see the use of moving it however.  It's easier if I just do that in the code, instead of accepting the PR, so I'll close it. . Expect the change to be in the next version though! 

Thanks for the submit.

**Comment by krestaino** [comment]
Awesome, thank you!

**Comment by krestaino** [comment]
@bschuiling Hello! Just wanted to follow up here. Any chance you can add this functionality and publish a new version of the plugin?

**Comment by bschuiling** [comment]
We don't have much other updates ready for this plugin. But if you really need it, you can just use the updates branch for a while, and later upgrade to a release version - https://github.com/short-pixel-optimizer/enable-media-replace/tree/updates

**Pull request closed without merging**
